/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Apartment } from "./Apartment";
import { ApartmentCountArgs } from "./ApartmentCountArgs";
import { ApartmentFindManyArgs } from "./ApartmentFindManyArgs";
import { ApartmentFindUniqueArgs } from "./ApartmentFindUniqueArgs";
import { CreateApartmentArgs } from "./CreateApartmentArgs";
import { UpdateApartmentArgs } from "./UpdateApartmentArgs";
import { DeleteApartmentArgs } from "./DeleteApartmentArgs";
import { FavoriteFindManyArgs } from "../../favorite/base/FavoriteFindManyArgs";
import { Favorite } from "../../favorite/base/Favorite";
import { QuestionnaireFindManyArgs } from "../../questionnaire/base/QuestionnaireFindManyArgs";
import { Questionnaire } from "../../questionnaire/base/Questionnaire";
import { ApartmentService } from "../apartment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Apartment)
export class ApartmentResolverBase {
  constructor(
    protected readonly service: ApartmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Apartment",
    action: "read",
    possession: "any",
  })
  async _apartmentsMeta(
    @graphql.Args() args: ApartmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Apartment])
  @nestAccessControl.UseRoles({
    resource: "Apartment",
    action: "read",
    possession: "any",
  })
  async apartments(
    @graphql.Args() args: ApartmentFindManyArgs
  ): Promise<Apartment[]> {
    return this.service.apartments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Apartment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Apartment",
    action: "read",
    possession: "own",
  })
  async apartment(
    @graphql.Args() args: ApartmentFindUniqueArgs
  ): Promise<Apartment | null> {
    const result = await this.service.apartment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Apartment)
  @nestAccessControl.UseRoles({
    resource: "Apartment",
    action: "create",
    possession: "any",
  })
  async createApartment(
    @graphql.Args() args: CreateApartmentArgs
  ): Promise<Apartment> {
    return await this.service.createApartment({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Apartment)
  @nestAccessControl.UseRoles({
    resource: "Apartment",
    action: "update",
    possession: "any",
  })
  async updateApartment(
    @graphql.Args() args: UpdateApartmentArgs
  ): Promise<Apartment | null> {
    try {
      return await this.service.updateApartment({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Apartment)
  @nestAccessControl.UseRoles({
    resource: "Apartment",
    action: "delete",
    possession: "any",
  })
  async deleteApartment(
    @graphql.Args() args: DeleteApartmentArgs
  ): Promise<Apartment | null> {
    try {
      return await this.service.deleteApartment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Favorite], { name: "favorites" })
  @nestAccessControl.UseRoles({
    resource: "Favorite",
    action: "read",
    possession: "any",
  })
  async findFavorites(
    @graphql.Parent() parent: Apartment,
    @graphql.Args() args: FavoriteFindManyArgs
  ): Promise<Favorite[]> {
    const results = await this.service.findFavorites(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Questionnaire], { name: "questionnaires" })
  @nestAccessControl.UseRoles({
    resource: "Questionnaire",
    action: "read",
    possession: "any",
  })
  async findQuestionnaires(
    @graphql.Parent() parent: Apartment,
    @graphql.Args() args: QuestionnaireFindManyArgs
  ): Promise<Questionnaire[]> {
    const results = await this.service.findQuestionnaires(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
