/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsInt,
  ValidateNested,
} from "class-validator";
import { FavoriteCreateNestedManyWithoutApartmentsInput } from "./FavoriteCreateNestedManyWithoutApartmentsInput";
import { Type } from "class-transformer";
import { QuestionnaireCreateNestedManyWithoutApartmentsInput } from "./QuestionnaireCreateNestedManyWithoutApartmentsInput";

@InputType()
class ApartmentCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  area?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  etage?: number | null;

  @ApiProperty({
    required: false,
    type: () => FavoriteCreateNestedManyWithoutApartmentsInput,
  })
  @ValidateNested()
  @Type(() => FavoriteCreateNestedManyWithoutApartmentsInput)
  @IsOptional()
  @Field(() => FavoriteCreateNestedManyWithoutApartmentsInput, {
    nullable: true,
  })
  favorites?: FavoriteCreateNestedManyWithoutApartmentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  landlord?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postalCode?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => QuestionnaireCreateNestedManyWithoutApartmentsInput,
  })
  @ValidateNested()
  @Type(() => QuestionnaireCreateNestedManyWithoutApartmentsInput)
  @IsOptional()
  @Field(() => QuestionnaireCreateNestedManyWithoutApartmentsInput, {
    nullable: true,
  })
  questionnaires?: QuestionnaireCreateNestedManyWithoutApartmentsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  roomsCount?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { ApartmentCreateInput as ApartmentCreateInput };
